# Generated by Django 5.2.15 on 2026-06-04 09:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssetEngagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.CharField(help_text="Identifier of the catalog asset, e.g. 'mat-000123'.", max_length=64)),
                ('metric', models.CharField(choices=[('view', 'View'), ('download', 'Download'), ('rating', 'Rating')], help_text='The type of engagement recorded.', max_length=16)),
                ('value', models.FloatField(help_text='Magnitude of the event. 1.0 for a view/download; a 1-5 star score for a rating.', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('recorded_at', models.DateTimeField(db_index=True, help_text='When the engagement occurred (UTC).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'asset_engagement',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['asset_id', 'metric'], name='idx_asset_metric'), models.Index(fields=['metric', '-recorded_at'], name='idx_metric_time')],
                'constraints': [models.CheckConstraint(condition=models.Q(('value__gte', 0.0)), name='engagement_value_non_negative')],
            },
        ),
    ]
